;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				end-of-visual-line
				ess-smart-comma
				ess-yank
				kill-region
				org-self-insert-command
				))

(setq mc/cmds-to-run-once
      '(
				ccm-mwheel-scroll
				help-for-help
				))
